name: Assertions and static report

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          npm install -g @unlighthouse/cli puppeteer
          sudo apt-get update && sudo apt-get install ruby -y
      - name: Ensure Output Directory Exists
        run: mkdir -p .unlighthouse/dist

      - name: Unlighthouse Assertions and Client
        run: unlighthouse-ci --site http://51.44.25.104/en --build-static --output-path .unlighthouse/dist

      - name: Add Ruby Script for JSON to CSV
        run: |
          echo "require 'json'
          require 'csv'
          input_file = '.unlighthouse/dist/ci-result.json'
          output_file = '.unlighthouse/dist/ci-result.csv'
          begin
            json_data = JSON.parse(File.read(input_file))
            CSV.open(output_file, 'w', write_headers: true, headers: json_data.first.keys) do |csv|
              json_data.each do |row|
                csv << row.values
              end
            end
            puts \"CSV file created successfully: #{output_file}\"
          rescue Errno::ENOENT
            puts \"File not found: #{input_file}\"
          rescue JSON::ParserError => e
            puts \"Error parsing JSON: #{e.message}\"
          end" > convert_json_to_csv.rb
      - name: Process JSON to CSV
        run: ruby convert_json_to_csv.rb

      - name: Debug Processed Files
        run: ls -R .unlighthouse/dist

      - name: Upload Unlighthouse Report
        uses: actions/upload-artifact@v3
        with:
          name: unlighthouse-report
          path: .unlighthouse/dist/**
