name: Assertions and static report

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          npm install -g @unlighthouse/cli puppeteer
          sudo apt-get update && sudo apt-get install ruby -y

      - name: Unlighthouse Assertions and Client
        run: unlighthouse-ci --site http://51.44.25.104/en --build-static --output-path .unlighthouse/dist

      - name: Convert JSON to CSV
        run: ruby scripts/convert_json_to_csv.rb .unlighthouse/dist/ci-result.json .unlighthouse/dist/ci-result.csv

      - name: Upload Unlighthouse Report
        uses: actions/upload-artifact@v4
        with:
          name: unlighthouse-report
          path: .unlighthouse/dist/**
